apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-build-mcp.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "docker-build-mcp.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "docker-build-mcp.fullname" . }}
    spec:
      containers:
      - name: build-mcp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: docker-config
          mountPath: /root/.docker
      volumes:
      - name: docker-config
        secret:
          secretName: {{ .Values.secretName }}
          items:
          - key: config.json
            path: config.json
