apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server-kubernetes
  template:
    metadata:
      labels:
        app: mcp-server-kubernetes
    spec:
      containers:
      - name: mcp-server-kubernetes
        image: flux159/mcp-server-kubernetes
        imagePullPolicy: Always
        env:
        - name: ENABLE_UNSAFE_SSE_TRANSPORT
          value: "1"
        - name: PORT
          value: "3001"
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: kubeconfig
          mountPath: /home/appuser/.kube
      volumes:
      - name: kubeconfig
        secret:
          secretName: my-kubeconfig
          items:
          - key: config
            path: config
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server-kubernetes
spec:
  selector:
    app: mcp-server-kubernetes
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 32001
  type: NodePort
